"""add disc column

Revision ID: 20252200d08d
Revises: 821e0fa19ffb
Create Date: 2025-09-22 21:02:25.981054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20252200d08d'
down_revision = '821e0fa19ffb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saves', schema=None) as batch_op:
        batch_op.add_column(sa.Column('disc', sa.Integer(), nullable=False, server_default='0'))
        batch_op.execute("UPDATE disc SET ")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saves', schema=None) as batch_op:
        batch_op.drop_column('disc')

    # ### end Alembic commands ###
