"""empty message

Revision ID: 2fa478f1979e
Revises: aaaa98f5b4e5
Create Date: 2025-04-08 21:54:08.588526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fa478f1979e'
down_revision = 'aaaa98f5b4e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('party', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('party', schema=None) as batch_op:
        batch_op.drop_column('level')

    # ### end Alembic commands ###
