"""add party save id

Revision ID: a3fcc928a679
Revises: a0bd19652724
Create Date: 2025-06-27 22:03:25.771736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3fcc928a679'
down_revision = 'a0bd19652724'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('party', schema=None) as batch_op:
        batch_op.add_column(sa.Column('save_id', sa.String(), nullable=False))

    with op.batch_alter_table('saves', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.CHAR(length=32),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text('(gen_random_uuid())'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saves', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.String(),
               type_=sa.CHAR(length=32),
               existing_nullable=False,
               existing_server_default=sa.text('(gen_random_uuid())'))

    with op.batch_alter_table('party', schema=None) as batch_op:
        batch_op.drop_column('save_id')

    # ### end Alembic commands ###
