"""add type and remove level from materia table

Revision ID: a760c1d5f774
Revises: 0aaaeec19ba7
Create Date: 2025-10-30 21:39:41.732022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a760c1d5f774'
down_revision = '0aaaeec19ba7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('materia', schema=None) as batch_op:
        batch_op.drop_column('level')
        batch_op.add_column(sa.Column('type', sa.String(length=15), nullable=False, server_default='none'))
        batch_op.alter_column('name', existing_type=sa.String(length=15))
        batch_op.alter_column('element', existing_type=sa.String(length=10), type_=sa.String(length=20))

def downgrade():
    with op.batch_alter_table('materia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level', sa.Integer(), nullable=False, server_default=sa.text('1')))
        batch_op.alter_column('name', existing_type=sa.String(length=30))
        batch_op.alter_column('element', existing_type=sa.String(length=20), type_=sa.String(length=10))
        batch_op.drop_column('type')