"""add user_id and tidy constraints

Revision ID: b8a266fb802c
Revises: a760c1d5f774
Create Date: 2026-08-13 23:13:43.993848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8a266fb802c'
down_revision = 'a760c1d5f774'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_characters_name', ['name'])

    with op.batch_alter_table('enemies', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_enemies_name', ['name'])

    with op.batch_alter_table('materia', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=15),
               existing_nullable=False)
        batch_op.alter_column('element',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=15),
               existing_nullable=True)
        batch_op.create_unique_constraint('uq_materia_name', ['name'])

    with op.batch_alter_table('party', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uix_saveid_name'), type_='unique')
        batch_op.drop_column("name")
        batch_op.drop_column("level")
        batch_op.create_unique_constraint('uq_party_save_id', ['save_id'])
        batch_op.create_foreign_key('fk_party_save_id', 'saves', ['save_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('saves', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.UUID(), nullable=False))
        batch_op.create_index(batch_op.f('ix_saves_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saves', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_saves_user_id'))
        batch_op.drop_column('user_id')

    with op.batch_alter_table('party', schema=None) as batch_op:
        batch_op.drop_constraint('fk_party_save_id', type_='foreignkey')
        batch_op.drop_constraint('uq_party_save_id', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uix_saveid_name'), ['save_id', 'name'])

    with op.batch_alter_table('materia', schema=None) as batch_op:
        batch_op.drop_constraint('uq_materia_name', type_='unique')
        batch_op.alter_column('element',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)

    with op.batch_alter_table('enemies', schema=None) as batch_op:
        batch_op.drop_constraint('uq_enemies_name', type_='unique')

    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_constraint('uq_characters_name', type_='unique')

    # ### end Alembic commands ###
