"""modify party member pk to uuid

Revision ID: bd52fd790aab
Revises: ff9155b30553
Create Date: 2026-08-30 21:46:06.782915

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "bd52fd790aab"
down_revision = "ff9155b30553"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("party_member", schema=None) as batch_op:
        batch_op.drop_constraint(
            "fk_party_member_party_id",
            type_="foreignkey",
        )
        batch_op.alter_column(
            "party_id",
            existing_type=sa.INTEGER(),
            type_=sa.String(),
            existing_nullable=False,
        )
        batch_op.create_unique_constraint(
            "uq_party_member_party_name", ["party_id", "name"]
        )

    with op.batch_alter_table("party", schema=None) as batch_op:
        batch_op.alter_column(
            "id", existing_type=sa.INTEGER(), type_=sa.String(), existing_nullable=False
        )

    with op.batch_alter_table("party_member", schema=None) as batch_op:
        batch_op.create_foreign_key(
            "fk_party_member_party_id",
            "party",
            ["party_id"],
            ["id"],
            ondelete="CASCADE",
        )

    with op.batch_alter_table("saves", schema=None) as batch_op:
        batch_op.alter_column(
            "user_id",
            existing_type=sa.NUMERIC(),
            type_=sa.UUID(),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("saves", schema=None) as batch_op:
        batch_op.alter_column(
            "user_id",
            existing_type=sa.UUID(),
            type_=sa.NUMERIC(),
            existing_nullable=False,
        )

    with op.batch_alter_table("party_member", schema=None) as batch_op:
        batch_op.drop_constraint(
            "fk_party_member_party_id",
            type_="foreignkey",
        )

    with op.batch_alter_table("party", schema=None) as batch_op:
        batch_op.alter_column(
            "id",
            existing_type=sa.String(),
            type_=sa.INTEGER(),
            existing_nullable=False,
        )

    with op.batch_alter_table("party_member", schema=None) as batch_op:
        batch_op.alter_column(
            "party_id",
            existing_type=sa.String(),
            type_=sa.INTEGER(),
            existing_nullable=False,
        )
        batch_op.drop_constraint("uq_party_member_party_name", type_="unique")
    # ### end Alembic commands ###
