"""empty message

Revision ID: dce8616b95d4
Revises: e30ce2bf6f26
Create Date: 2025-04-19 21:36:45.475222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dce8616b95d4'
down_revision = 'e30ce2bf6f26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('weapon', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('enemies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('hp', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('steal', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('disc', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('materia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('element', sa.String(length=10), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('party',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('party_materia',
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('materia_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('member_id'),
    sa.UniqueConstraint('materia_id'),
    sa.UniqueConstraint('member_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('party_materia')
    op.drop_table('party')
    op.drop_table('materia')
    op.drop_table('enemies')
    op.drop_table('characters')
    # ### end Alembic commands ###
