"""empty message

Revision ID: e30ce2bf6f26
Revises: 2fa478f1979e
Create Date: 2025-04-08 22:09:11.136648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e30ce2bf6f26'
down_revision = '2fa478f1979e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('party', schema=None) as batch_op:
        batch_op.alter_column('level',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('party', schema=None) as batch_op:
        batch_op.alter_column('level',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
