# chat GPT-5 gave me this list below, if there's a materia missing, please let me know!

materia_data = [
    # Magic Materia
    {"name": "Fire", "type": "magic", "element": "fire"},
    {"name": "Ice", "type": "magic", "element": "ice"},
    {"name": "Lightning", "type": "magic", "element": "lightning"},
    {"name": "Earth", "type": "magic", "element": "earth"},
    {"name": "Restore", "type": "magic", "element": ""},
    {"name": "Heal", "type": "magic", "element": None},
    {"name": "Revive", "type": "magic", "element": None},
    {"name": "Seal", "type": "magic", "element": None},
    {"name": "Mystify", "type": "magic", "element": None},
    {"name": "Transform", "type": "magic", "element": None},
    {"name": "Exit", "type": "magic", "element": None},
    {"name": "Poison", "type": "magic", "element": "poison"},
    {"name": "Gravity", "type": "magic", "element": "gravity"},
    {"name": "Comet", "type": "magic", "element": "non-elemental"},
    {"name": "Barrier", "type": "magic", "element": None},
    {"name": "Destruct", "type": "magic", "element": None},
    {"name": "Time", "type": "magic", "element": "time"},
    {"name": "Contain", "type": "magic", "element": "mixed"},
    {"name": "Full Cure", "type": "magic", "element": ""},
    {"name": "Shield", "type": "magic", "element": None},
    {"name": "Ultima", "type": "magic", "element": "non-elemental"},
    {"name": "Master Magic", "type": "magic", "element": "various"},

    # Command Materia
    {"name": "Steal", "type": "command", "element": None},
    {"name": "Sense", "type": "command", "element": None},
    {"name": "Throw", "type": "command", "element": None},
    {"name": "Morph", "type": "command", "element": None},
    {"name": "Deathblow", "type": "command", "element": None},
    {"name": "Manipulate", "type": "command", "element": None},
    {"name": "Mime", "type": "command", "element": None},
    {"name": "Enemy Skill", "type": "command", "element": "various"},
    {"name": "Slash-All", "type": "command", "element": None},
    {"name": "Double Cut", "type": "command", "element": None},
    {"name": "W-Magic", "type": "command", "element": None},
    {"name": "W-Summon", "type": "command", "element": None},
    {"name": "W-Item", "type": "command", "element": None},
    {"name": "Master Command", "type": "command", "element": "various"},

    # Summon Materia
    {"name": "Choco/Mog", "type": "summon", "element": "wind"},
    {"name": "Shiva", "type": "summon", "element": "ice"},
    {"name": "Ifrit", "type": "summon", "element": "fire"},
    {"name": "Ramuh", "type": "summon", "element": "lightning"},
    {"name": "Titan", "type": "summon", "element": "earth"},
    {"name": "Odin", "type": "summon", "element": "non-elemental"},
    {"name": "Leviathan", "type": "summon", "element": "water"},
    {"name": "Bahamut", "type": "summon", "element": "non-elemental"},
    {"name": "Kujata", "type": "summon", "element": "fire/ice/lightning"},
    {"name": "Alexander", "type": "summon", "element": "holy"},
    {"name": "Phoenix", "type": "summon", "element": "fire"},
    {"name": "Neo Bahamut", "type": "summon", "element": "non-elemental"},
    {"name": "Hades", "type": "summon", "element": "poison"},
    {"name": "Typoon", "type": "summon", "element": "wind"},
    {"name": "Bahamut ZERO", "type": "summon", "element": "non-elemental"},
    {"name": "Knights of the Round", "type": "summon", "element": "non-elemental"},
    {"name": "Master Summon", "type": "summon", "element": "various"},

    # Support Materia
    {"name": "All", "type": "support", "element": None},
    {"name": "Elemental", "type": "support", "element": None},
    {"name": "Added Effect", "type": "support", "element": None},
    {"name": "MP Absorb", "type": "support", "element": None},
    {"name": "HP Absorb", "type": "support", "element": None},
    {"name": "MP Turbo", "type": "support", "element": None},
    {"name": "Added Cut", "type": "support", "element": None},
    {"name": "Steal as well", "type": "support", "element": None},
    {"name": "Sneak Attack", "type": "support", "element": None},
    {"name": "Counter", "type": "support", "element": None},
    {"name": "Magic Counter", "type": "support", "element": None},
    {"name": "Final Attack", "type": "support", "element": None},
    {"name": "Quadra Magic", "type": "support", "element": None},
    {"name": "Underwater", "type": "support", "element": None},

    # Independent Materia
    {"name": "HP Plus", "type": "independent", "element": None},
    {"name": "MP Plus", "type": "independent", "element": None},
    {"name": "Speed Plus", "type": "independent", "element": None},
    {"name": "Magic Plus", "type": "independent", "element": None},
    {"name": "Luck Plus", "type": "independent", "element": None},
    {"name": "EXP Plus", "type": "independent", "element": None},
    {"name": "Gil Plus", "type": "independent", "element": None},
    {"name": "Enemy Lure", "type": "independent", "element": None},
    {"name": "Enemy Away", "type": "independent", "element": None},
    {"name": "Chocobo Lure", "type": "independent", "element": None},
    {"name": "Pre-emptive", "type": "independent", "element": None},
    {"name": "Long Range", "type": "independent", "element": None},
    {"name": "Mega All", "type": "independent", "element": None},
    {"name": "Cover", "type": "independent", "element": None},
    {"name": "Counter Attack", "type": "independent", "element": None},
    {"name": "Slash-All", "type": "independent", "element": None},
    {"name": "Underwater", "type": "independent", "element": None},
]