name: Upgrade prod db
on:
  push: 
    branches:
      - main
  workflow_dispatch:
    inputs:
      upgrade_prod:
        description: 'Upgrade prod?'
        type: boolean
        required: true
        default: false
jobs:
  validate_inputs:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Print choice
        run: echo "${{ github.event.inputs.upgrade_prod }}"
      
      - name: Validate choice
        if: ${{ github.event.inputs.upgrade_prod == 'false' }}
        run: |
          echo "'No' was selected, quitting workflow"
          exit 1

  upgrade:
    needs: validate_inputs
    runs-on: ubuntu-latest
    environment: prod
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install python requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Upgrade db
        run: |
          flask db current
          flask db heads
          flask db upgrade