name: Run migration

on:
  push: 
    branches:
      - workflow-migrate-trigger
  workflow_dispatch:
    inputs:
      choice:
        type: choice
        description: 'Run prod migration?'
        options:
          - yes
          - no

jobs:
  install:
    runs-on: ubuntu-latest

    environment: dev
    
    steps:
    - name: Send greeting
      run: echo "Hello ${{ inputs.choice }}"

    - name: Print env var
      run: echo "env var value is >${{ vars.VAR }}<"

    - name: Get secret name
      run: echo "env secret value is ${{ secrets.NAME }}"

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

  show_routes:
    needs: install
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: flask verify
      run: flask routes

    
  