name: Upgrade prod db
on:
  push: 
    branches:
      - main
      - modify-deploy-workflow
  workflow_dispatch:
    inputs:
      choice:
        description: 'Update prod?'
        required: true
        default: 'no'

jobs:
  validate_inputs:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Print choice
        run: echo "${{ github.event.inputs.choice }}"
      
      - name: Validate choice
        if: ${{ github.event.inputs.choice == 'no' }}
        run: |
          echo "Choice is to not update prod db, quitting workflow"
          exit 1

  python:
    needs: validate_inputs
    runs-on: ubuntu-latest
    environment: prod
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install python requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run db migration
        run: |
          flask db current
          flask db heads
          flask db upgrade