name: Run migration

on:
  push: 
    branches:
      - main
      - modify-deploy-workflow
  workflow_dispatch:
    inputs:
      environment:
        description: 'Run migration?'
        required: true
        default: 'no'

jobs:
  validate_inputs:
    runs-on: ubuntu-latest

    environment: prod
    
    steps:
      - name: Validate environment
        if: ${{ inputs.environment == 'no' }}
        run: |
          echo "Quitting workflow"
          exit 1

  python:
    needs: validate_inputs
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install python requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Print Flask routes
        run: flask routes

    
  
